project:
  type: website

website:
  title: "Kevin Navarrete-Parra"
  site-url: "https://kevinnavreteparra.github.io/kevin-quarto-blog/"
  description: "A place for my notes and thoughts on political science, data science, and research methods"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Posts
      # - href: projects.qmd
      #   text: Projects
      - href: presentations.qmd
        text: Presentations
      # - href: cv.qmd
      #   text: CV
    right:
      - icon: github
        href: https://github.com/KevinNavarreteParra
      - icon: linkedin
        href: https://www.linkedin.com/in/kevin-navarrete-parra
      - icon: rss
        href: index.xml
        
  page-footer:
    center: |
      © 2025 Kevin Navarrete-Parra. All rights reserved.
    background: primary

  google-analytics: 
    tracking-id: ${GOOGLE_ANALYTICS_ID}
    storage: none
    anonymize-ip: true
  cookie-consent: false
  open-graph: true


format:
  html:
    theme: 
      - morph
      - custom.scss
    css: styles.css
    toc: true
    toc-depth: 3
    html-math-method: katex
    citations-hover: true
    footnotes-hover: true
    code-fold: show
    code-tools: true
    fig-width: 8
    fig-height: 6

execute:
  freeze: auto

engines:
  - knitr
  - jupyter

jupyter: python3

knitr:
  opts_chunk:
    python.reticulate: false
  opts_knit:
    python.cmd: py
