---
author: Kevin Navarrete-Parra
categories:
- PhD
date: '2025-01-18'
description: I finished my prospectus and I'm looking forward to my defense.
draft: false
format: html
title: I Just Finished My Prospectus
toc: true
---

A part of me wants to start writing more things that aren't academic. I'd like to write about what's on my mind or about things that I find interesting--even if nobody is reading--but my degree progression consumers so much time that I rarely get the chance to do so. Starting this year, I'd like to make an effort to change that. Like I said, even if nobody is reading what I'm writing. I think it would be fun for posterity, and engaging in this type of writing might help me think more clearly about what I'm doing in the aggregate, which can be challenging when pushing through everything, one day at a time. 

To that end, I think a good starting point is to try to write somewhat regularly about my progress through the PhD program--maybe about what I feel I've accomplished or learned in a given week. Now, I'm well aware that I said I want to write things that aren't academic, and that what I'm proposing here is to write about the part of my life that is academic. But come on, I've got to start somewhere, and I think that writing sort of informally about what's going on in this part of my life is distant enough from the academic writing I'm doing for my degree that I can scratch that writing itch I have. 

With that house keeping out of the way, I just finished my prospectus yesterday. I felt pretty good about hitting that milestone. I'm well aware that this is only one part of a two-step process that is a prospectus defense, so I know I'm not out of the woods yet. Nevertheless, it felt good to get that document written and out of the way and sent to my committee. I've also gotten responses from all of my committee members regarding the defense date; it's looking like we'll be meeting at the end of January. The exact time is uncertain at this point--I still have to hear back from one of my committee members' administrative assistant about his schedule--but I'm eager for my work to make it through that first crucible. I know my four committee member won't go easy on me, and I'm confident their comments will be biting, but incredibly insightful and constructive. 

Having finished my prospectus, I'm struck by a feeling that has been relatively common throughout my degree progression. There's this almost necessary level of solitude that pervades most aspects of my degree progression. I'm not saying that there aren't people around to talk with about my work or that I don't have a support system--I'd say quite the opposite is true, in fact. No, there is a solitude that comes in the moment of rejoicing in the completion of a task. I can tell my friends and family that I did this thing, and I can talk to any number of people about everything that went into what I've done. And they'll all express their congratulations or their well wishes, which is nice. But I can't escape this feeling of solitude that comes about following a task's completion. 

Now, I'm not saying that nobody understands what I'm doing or that nobody can relate. Everyone in my life understands and they all relate to most, if not all, I'm going through here. This is especially the case with my friends in the program, who are quite literally undergoing the same experience. After all, undertaking a PhD is not so substantively different from other types of work that it's impossible or even difficult to relate to.

I think the feeling of solitude comes from how much of myself I've put into my research, how much of my time and how many of my thoughts I've dedicated to this endeavor so far. And this goes for the prospectus, of course, but also for the broader undertaking as a whole, including my coursework, research, conference travel, and anything else that can be reasonably included under my degree progression umbrella.

I spend most of my time thinking about this project, the data I'll keep collecting, and helpful code I can write to make the process more efficient. I'll think about potential article ideas and about moves I can make to add another line to my CV. I think I've trapped myself, thinking constantly in terms of me and what I can and should do next. When it comes to rejoicing in a tangible accomplishment, I can't help but default to the same mindset: solitude resulting from the single-minded need to succeed. 

Despite the solitude, I don't necessarily see a message of sadness in this. What I said above may be the case, but I nevertheless feel excited for what will come next. It does bring me joy to share my accomplishment with my friends and family, and I am earnestly looking forward to what my committee will say about where my research is heading. I also feel this underlying sense that I'm exactly where I've always wanted to be doing precisely what I've always wanted to do--even if I never could have imagine the granular details of what I'm doing now. Not only am I happy in the moment, I am content with the aggregate of my experiences so far, which I think is far more challenging to achieve.

Now that this prospectus is done, I have plenty to be happy about, plenty to be thankful for. I am motivated to keep pushing. And, importantly, I'm looking forward to my defense, which will be the next step in this long journey. I hope I get to write about a successful defense soon. 