name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install R and dependencies
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install R packages
        run: |
          if (file.exists("renv.lock")) {
            install.packages("renv")
            renv::restore()
          }
        shell: Rscript {0}
      
      - name: Secure Build and Publish
        run: |
          # Make build script executable
          chmod +x build.sh
          
          # Run secure build with environment variables
          ./build.sh
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
      
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: _site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
